server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rating_microservice
    username: root
    password: satyam
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
  application:
    name: RATING-SERVICE

eureka:
  instance:
   prefer-ip-address: true
  client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
      defaultzone: http://localhost:8761/eureka
      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health    
  endpoint:
    health:
      show-details: always
  
resilience4j:
  circuitbreaker:
    instances:
      hotelbreaker1:
       register-health-indicator: true
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 5
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 6s
       permitted-number-of-calls-in-half-open-state: 3
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED
       
       
       
      hotelbreaker2:
       register-health-indicator: true
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 5
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 6s
       permitted-number-of-calls-in-half-open-state: 3
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED     